@echo off                     
rem This PiLibSDK library supports only CF_A8, CF_B8G8R8 and CF_A8B8G8R8 formats.
..\..\..\..\_tools\BinC\BinC background.jpg background.cpp BackgroundImgJPG
..\..\..\..\_tools\BinC\BinC blacksredsCZ.png blacksredsCZ.cpp BlacksRedsCZImgPNG
..\..\..\..\_tools\BinC\BinC blacksredsEN.png blacksredsEN.cpp BlacksRedsENImgPNG
..\..\..\..\_tools\BinC\BinC cardbase.png cardbase.cpp CardBaseImgPNG
..\..\..\..\_tools\BinC\BinC cardimage.png cardimage.cpp CardImagePNG
..\..\..\..\_tools\BinC\BinC cardtextCZ.png cardtextCZ.cpp CardTextCZImgPNG
..\..\..\..\_tools\BinC\BinC cardtextEN.png cardtextEN.cpp CardTextENImgPNG
..\..\..\..\_tools\BinC\BinC castle.png castle.cpp CastleImgPNG
..\..\..\..\_tools\BinC\BinC castle_shadow.png castle_shadow.cpp CastleShadowImgPNG
..\..\..\..\_tools\BinC\BinC cloud.png cloud.cpp CloudImgPNG
..\..\..\..\_tools\BinC\BinC cursor.png cursor.cpp CursorImgPNG
..\..\..\..\_tools\BinC\BinC discardCZ.png discardCZ.cpp DiscardCZImgPNG
..\..\..\..\_tools\BinC\BinC discardEN.png discardEN.cpp DiscardENImgPNG
..\..\..\..\_tools\BinC\BinC fence.png fence.cpp FenceImgPNG
..\..\..\..\_tools\BinC\BinC fence_shadow.png fence_shadow.cpp FenceShadowImgPNG
..\..\..\..\_tools\BinC\BinC flags.png flags.cpp FlagsImgPNG
..\..\..\..\_tools\BinC\BinC grass.png grass.cpp GrassImgPNG
..\..\..\..\_tools\BinC\BinC lang.png lang.cpp LangImgPNG
..\..\..\..\_tools\BinC\BinC open.png open.cpp OpenImgPNG
..\..\..\..\_tools\BinC\BinC open_sel.png open_sel.cpp OpenSelImgPNG
..\..\..\..\_tools\BinC\BinC open_sel2.png open_sel2.cpp OpenSel2ImgPNG
..\..\..\..\_tools\BinC\BinC opentextCZ.png opentextCZ.cpp OpenTextCZImgPNG
..\..\..\..\_tools\BinC\BinC opentextEN.png opentextEN.cpp OpenTextENImgPNG
..\..\..\..\_tools\BinC\BinC select.png select.cpp SelectImgPNG
..\..\..\..\_tools\BinC\BinC state.png state.cpp StateImgPNG
..\..\..\..\_tools\BinC\BinC stateCZ.png stateCZ.cpp StateCZImgPNG
..\..\..\..\_tools\BinC\BinC stateEN.png stateEN.cpp StateENImgPNG
..\..\..\..\_tools\BinC\BinC titleCZ.png titleCZ.cpp TitleCZImgPNG
..\..\..\..\_tools\BinC\BinC titleEN.png titleEN.cpp TitleENImgPNG
..\..\..\..\_tools\BinC\BinC title2CZ.png title2CZ.cpp Title2CZImgPNG
..\..\..\..\_tools\BinC\BinC title2EN.png title2EN.cpp Title2ENImgPNG
..\..\..\..\_tools\BinC\BinC title3_1.png title3_1.cpp Title3_1ImgPNG
..\..\..\..\_tools\BinC\BinC title3_3.png title3_3.cpp Title3_3ImgPNG
..\..\..\..\_tools\BinC\BinC title3_4.png title3_4.cpp Title3_4ImgPNG
..\..\..\..\_tools\BinC\BinC trumpet.png trumpet.cpp TrumpetImgPNG
..\..\..\..\_tools\BinC\BinC win.png win.cpp WinImgPNG
