@echo off
..\..\..\..\_tools\PiLibSnd\PiLibSnd bigbonus.wav     bigbonus.cpp     BigbonusSnd
..\..\..\..\_tools\PiLibSnd\PiLibSnd blackhole.wav    blackhole.cpp    BlackholeSnd
..\..\..\..\_tools\PiLibSnd\PiLibSnd blackhole2.wav   blackhole2.cpp   Blackhole2Snd
..\..\..\..\_tools\PiLibSnd\PiLibSnd electricity.wav  electricity.cpp  ElectricitySnd
..\..\..\..\_tools\PiLibSnd\PiLibSnd enemyhit.wav     enemyhit.cpp     EnemyhitSnd
..\..\..\..\_tools\PiLibSnd\PiLibSnd fail.wav         fail.cpp         FailSnd
..\..\..\..\_tools\PiLibSnd\PiLibSnd flame.wav        flame.cpp        FlameSnd
..\..\..\..\_tools\PiLibSnd\PiLibSnd glass.wav        glass.cpp        GlassSnd
..\..\..\..\_tools\PiLibSnd\PiLibSnd gun.wav          gun.cpp          GunSnd
..\..\..\..\_tools\PiLibSnd\PiLibSnd lasershot.wav    lasershot.cpp    LasershotSnd
..\..\..\..\_tools\PiLibSnd\PiLibSnd minigun.wav      minigun.cpp      MinigunSnd
..\..\..\..\_tools\PiLibSnd\PiLibSnd noise.wav        noise.cpp        NoiseSnd
..\..\..\..\_tools\PiLibSnd\PiLibSnd phasershot.wav   phasershot.cpp   PhasershotSnd
..\..\..\..\_tools\PiLibSnd\PiLibSnd rocketshot.wav   rocketshot.cpp   RocketshotSnd
..\..\..\..\_tools\PiLibSnd\PiLibSnd screaming.wav    screaming.cpp    ScreamingSnd
..\..\..\..\_tools\PiLibSnd\PiLibSnd swing.wav        swing.cpp        SwingSnd
..\..\..\..\_tools\PiLibSnd\PiLibSnd throw.wav        throw.cpp        ThrowSnd
..\..\..\..\_tools\PiLibSnd\PiLibSnd zing.wav         zing.cpp         ZingSnd

..\..\..\..\_tools\BinC\BinC music1.mp3   music1.cpp    Music1Snd
..\..\..\..\_tools\BinC\BinC music2.mp3   music2.cpp    Music2Snd
..\..\..\..\_tools\BinC\BinC music3.mp3   music3.cpp    Music3Snd
..\..\..\..\_tools\BinC\BinC music4.mp3   music4.cpp    Music4Snd
..\..\..\..\_tools\BinC\BinC music5.mp3   music5.cpp    Music5Snd
..\..\..\..\_tools\BinC\BinC music6.mp3   music6.cpp    Music6Snd
..\..\..\..\_tools\BinC\BinC music7.mp3   music7.cpp    Music7Snd
..\..\..\..\_tools\BinC\BinC music8.mp3   music8.cpp    Music8Snd
..\..\..\..\_tools\BinC\BinC music9.mp3   music9.cpp    Music9Snd
..\..\..\..\_tools\BinC\BinC music10.mp3  music10.cpp   Music10Snd
..\..\..\..\_tools\BinC\BinC music11.mp3  music11.cpp   Music11Snd
..\..\..\..\_tools\BinC\BinC music12.mp3  music12.cpp   Music12Snd
