M48
; DRILL file {KiCad 9.0.7} date 2026-04-04T22:04:30+0200
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-04-04T22:04:30+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.7
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.700
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.750
%
G90
G05
T1
X3.5Y-38.0
X3.5Y-96.5
X146.5Y-3.5
X146.5Y-38.0
X146.5Y-96.5
T2
X3.5Y-3.5
X3.5Y-26.5
X61.5Y-3.5
X61.5Y-26.5
M30
