
##############################################################################
#                      Architecture configuration
##############################################################################

# Path to root directory from the project directory (without trailing '/' delimiter)
PI_ROOT_PATH=../../..

# Makefile includes
include ${PI_ROOT_PATH}/Makefile1.mk

##############################################################################
#                             Input files
##############################################################################

# ASM source files
ASRC +=

# C source files
CSRC += img/test1.c
CSRC += img/test2.c
CSRC += img/test3.c
CSRC += snd/fanfare.c

# C++ source files
SRC += src/main.cpp

##############################################################################
#                         Library configuration
##############################################################################
# For available options see config_def.mk in root directory.

##############################################################################
#                         Font configuration
##############################################################################
# For available options see config_def.mk in root directory.

##############################################################################
#                         SDK configuration
##############################################################################
# For available options see config_def.mk in root directory.

##############################################################################
#                  Include build Makefile 2nd stage - Build
##############################################################################

# Makefile includes
include ${PI_ROOT_PATH}/Makefile2.mk
