
##############################################################################
#                      Architecture configuration
##############################################################################

# Path to root directory from the project directory (without trailing '/' delimiter)
PI_ROOT_PATH=../../..

# Makefile includes
include ${PI_ROOT_PATH}/Makefile1.mk

##############################################################################
#                             Input files
##############################################################################

# ASM source files
ASRC +=

# C source files
CSRC +=

# C++ source files
SRC += src/main.cpp

SRC += img/logo.cpp

#SRC += snd/001.cpp
#SRC += snd/002.cpp
#SRC += snd/003.cpp
#SRC += snd/004.cpp
#SRC += snd/005.cpp
#SRC += snd/006.cpp
#SRC += snd/007.cpp
#SRC += snd/008.cpp
#SRC += snd/009.cpp
#SRC += snd/010.cpp
#SRC += snd/011.cpp
#SRC += snd/012.cpp
#SRC += snd/013.cpp
#SRC += snd/014.cpp
#SRC += snd/015.cpp
#SRC += snd/016.cpp
#SRC += snd/017.cpp
#SRC += snd/018.cpp
#SRC += snd/019.cpp
#SRC += snd/020.cpp
#SRC += snd/021.cpp
#SRC += snd/022.cpp
#SRC += snd/023.cpp
#SRC += snd/024.cpp
#SRC += snd/025.cpp
#SRC += snd/026.cpp
#SRC += snd/027.cpp
#SRC += snd/028.cpp
#SRC += snd/029.cpp
#SRC += snd/030.cpp
#SRC += snd/031.cpp
#SRC += snd/032.cpp
#SRC += snd/033.cpp
#SRC += snd/034.cpp
#SRC += snd/035.cpp
#SRC += snd/036.cpp
#SRC += snd/037.cpp
#SRC += snd/038.cpp
#SRC += snd/039.cpp
#SRC += snd/040.cpp
#SRC += snd/041.cpp
#SRC += snd/042.cpp
#SRC += snd/043.cpp
#SRC += snd/044.cpp
#SRC += snd/045.cpp
#SRC += snd/046.cpp
#SRC += snd/047.cpp
#SRC += snd/048.cpp
#SRC += snd/049.cpp
#SRC += snd/050.cpp
#SRC += snd/051.cpp
#SRC += snd/052.cpp
#SRC += snd/053.cpp
#SRC += snd/054.cpp
#SRC += snd/055.cpp
#SRC += snd/056.cpp
#SRC += snd/057.cpp
#SRC += snd/058.cpp
#SRC += snd/059.cpp
#SRC += snd/060.cpp
#SRC += snd/061.cpp
#SRC += snd/062.cpp
#SRC += snd/063.cpp
#SRC += snd/064.cpp
#SRC += snd/065.cpp
#SRC += snd/066.cpp
#SRC += snd/067.cpp
#SRC += snd/068.cpp
#SRC += snd/069.cpp
#SRC += snd/070.cpp
#SRC += snd/071.cpp
#SRC += snd/072.cpp
#SRC += snd/073.cpp
#SRC += snd/074.cpp
#SRC += snd/075.cpp
#SRC += snd/076.cpp
#SRC += snd/077.cpp
#SRC += snd/078.cpp
#SRC += snd/079.cpp
#SRC += snd/080.cpp
#SRC += snd/081.cpp
#SRC += snd/082.cpp
#SRC += snd/083.cpp
#SRC += snd/084.cpp
#SRC += snd/085.cpp
#SRC += snd/086.cpp
#SRC += snd/087.cpp
#SRC += snd/088.cpp
#SRC += snd/089.cpp
#SRC += snd/090.cpp
#SRC += snd/091.cpp
#SRC += snd/092.cpp
#SRC += snd/093.cpp
#SRC += snd/094.cpp
#SRC += snd/095.cpp
#SRC += snd/096.cpp
#SRC += snd/097.cpp
#SRC += snd/098.cpp
#SRC += snd/099.cpp
#SRC += snd/100.cpp
#SRC += snd/101.cpp
#SRC += snd/102.cpp
#SRC += snd/103.cpp
#SRC += snd/104.cpp
#SRC += snd/105.cpp
#SRC += snd/106.cpp
#SRC += snd/107.cpp
#SRC += snd/108.cpp
#SRC += snd/109.cpp
#SRC += snd/110.cpp
#SRC += snd/111.cpp
#SRC += snd/112.cpp
#SRC += snd/113.cpp
#SRC += snd/114.cpp
#SRC += snd/115.cpp
#SRC += snd/116.cpp
#SRC += snd/117.cpp
#SRC += snd/118.cpp
#SRC += snd/119.cpp
#SRC += snd/120.cpp
#SRC += snd/121.cpp
#SRC += snd/122.cpp
#SRC += snd/123.cpp
#SRC += snd/124.cpp
#SRC += snd/125.cpp
#SRC += snd/126.cpp
#SRC += snd/127.cpp
#SRC += snd/128.cpp
#SRC += snd/129.cpp
#SRC += snd/130.cpp

##############################################################################
#                         Library configuration
##############################################################################
# For available options see config_def.mk in root directory.

# 1=use BIT integers, 0=not used (_lib/bigint/*)
USE_BIGINT=0

# 1=use MP3 decoder, 0=not used (mp3/lib_mp3.*)
USE_MP3=1

# 1=use PWM sound output, 0=not used (lib_pwmsnd.*)
USE_PWMSND=1

# 1=use REAL numbers, 0=not used (_lib/real/*)
USE_REAL=0

##############################################################################
#                         Font configuration
##############################################################################
# For available options see config_def.mk in root directory.

##############################################################################
#                         SDK configuration
##############################################################################
# For available options see config_def.mk in root directory.

##############################################################################
#                  Include build Makefile 2nd stage - Build
##############################################################################

# Makefile includes
include ${PI_ROOT_PATH}/Makefile2.mk
